load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "splash",
    srcs = ["Splash.cpp"],
    hdrs = ["Splash.hpp"],
    visibility = ["//src:__subpackages__"],
    deps = [
        "@ftxui//:component",
        "@ftxui//:dom",
        "@ftxui//:screen",
    ],
)
