load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "form_style",
    srcs = ["FormStyle.cpp"],
    hdrs = ["FormStyle.hpp"],
    visibility = ["//src:__subpackages__"],
    deps = [
        "@ftxui//:component",
        "@ftxui//:dom",
        "@ftxui//:screen",
    ],
)
