load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "models",
    hdrs = [
        "Result.hpp",
        "Task.hpp",
        "Workflow.hpp",
    ],
    visibility = ["//src:__subpackages__"],
)
