load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "scrollable",
    srcs = ["ScrollableNode.cpp"],
    hdrs = ["ScrollableNode.hpp"],
    visibility = ["//src:__subpackages__"],
    deps = [
        "@ftxui//:dom",
    ],
)
